### AI  > ML > Deep Learning > Neural Networks

# ANN
## Str of Neural Network (ANN)
### 3 Layers =>
- Input Layer : Data inputed to NN; Each Circle represents one feature (a piece of info); Circles mean's variables / data set fed into it
- Hidden layer 1 & 2 : processing
- Output layer : Result
* Perceptron : No Hidden layer; Direct from input to Output ; Linear classifier; has many limitations 
 
#### Comparison with Neuron :-
* Dendrite : refers to input 
* Axon : output delivered thru axon
    - width of dendrites define the weight associated with it
 
### ANN
- X1, X2 .... <= Input Layer
- Y1, Y2, ... <= Output Layer
-  S =  Σ X<sub>i</sub> W<sub>i</sub>
    - combinaions of X and W based on path for each prticular layer
- Hidden Layer : H1, H2, ...
- Wi <==> Weights  
- Bias  : less than 1; B1, B2, ...
- Activation with sigmoid fn => The output for a single layer (process of forward propagation)
- Z ==> S + bias
- Sigmoid Fn : $$ x = {\\  1 \over 1 + e^{-z} } $$ can also be taken as (1- e * x)
- Compare resulatant of ouput with Original value (given); if they are same, procedure can be stopped; if not we apply baclkward propation for updating weights
- Backward Propagation : resumes where we left off, ie; backward (from right-to-left)
    - New val of wi, $$ wi =  Old_Val_of_wi - [(eta_symbol) * derivative of { Error \over old_Val_of_wi } ]$$
    - ie; ivide, eta vechu all related weights for each output nokkanam/hidden layer 
        ie; differential of error for each dependant of Y<sub>i</sub> and/or H<sub>i</sub>
     - (eta) is,  learning rate  ; decimals less than 1
     - Chain rule of partial derivatives
     * Str reaches left End of first cycle of this process : End of first iteration
         1. Apply the same forward propagation;
         2. Check values
         3. If (!notEqual); 
            - Apply backward Propagation
         4. Else 
             - Procedure terminates when it's done. 
- Gradient--- procedure => uses derivations/ differential calc
- Gradient Descent
    - Error is taken by mean_quare_error
    - 
    - if this get's too complex, vanishing gradient will occur; procedures like LSDM is used
- Manual process takes more than an 1hr
- Steps :
    1. Get Inputs X1, X2, X3 ...
    2. Compute S, add bias to get Z
    3. Apply activation with sigmoid fn; marks end of forward propagation; to get resultant output
    4. Loop begins
    5. Updation of Weights : Checking as mentioned above
    - if found dissimilar; apply Backward Propagation until target value == output value
    6. Terminate Process

### Note : 
- RBM & Autoencoders
- DNN is ANN with multiple hidden layers
- CNN for image
- RNN for sequential data

    - Problems : Vanishing gradient, exploding gradient; Soln's like : LSDM
    - LSDM, GRU, Gated RNN, Noturn encoders
    
- Multilayer Perceptron == Deep Feedforward network === feedforward neural network
- z == linear regression; activation formular from logistical
- ANN - speech recognition, anomaly detection, audio generation, spell check
- Activation fn s :
 - Linear : fn is same as z
 - Step : if z less than 0, 0; greater than or equal to 0 ; is; like step fn in mathematics
 - Sigmpid : as above
 - Softmax : extension of sigmoid; e^x / summ of e^x; CNN; multiple inputs
 - ReLU : ; used for CNN
 - Hyperbolic : tanh
 $$ tanh = \frac{\\ e^x - e^-x}{e^x + e^-x} $$
 - loss fn - cross entropy(classification), log loss, hinge loss, exponential loss, 

### Practicals

#### Program 1

In [15]:
import numpy as np

In [16]:
in_sam = np.array([[1,0,1],[1,1,1],[0,1,0],[0,1,1]])
out_sam = np.array([[1],[1],[0],[0]])
in_sam

array([[1, 0, 1],
       [1, 1, 1],
       [0, 1, 0],
       [0, 1, 1]])

In [17]:
out_sam

array([[1],
       [1],
       [0],
       [0]])

In [18]:
#weights
#random.seed(); so that values remain same everytime we run
np.random.seed(10)
weights = np.random.random([3,1])
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [19]:
bias = 0.02 
sum = bias + np.dot(in_sam, weights)
sum


array([[1.42496888],
       [1.44572083],
       [0.04075195],
       [0.67440018]])

In [20]:
def activation(x):
    return 1/(1+np.exp(-x))
pred_out = activation(sum)
pred_out

array([[0.8061162 ],
       [0.80933899],
       [0.51018658],
       [0.66248773]])

In [21]:
error = out_sam - pred_out
error

array([[ 0.1938838 ],
       [ 0.19066101],
       [-0.51018658],
       [-0.66248773]])

when taking ; we must check whether matrix mult is possible or not #found by .shape
and then perform adjustment #adjustment.shape