### AI  > ML > Deep Learning > Neural Networks

# ANN
## Str of Neural Network (ANN)
### 3 Layers =>
- Input Layer : Data inputed to NN; Each Circle represents one feature (a piece of info); Circles mean's variables / data set fed into it
- Hidden layer 1 & 2 : processing
- Output layer : Result
* Perceptron : No Hidden layer; Direct from input to Output ; Linear classifier; has many limitations 
 
#### Comparison with Neuron :-
* Dendrite : refers to input 
* Axon : output delivered thru axon
    - width of dendrites define the weight associated with it
 
### ANN
- X1, X2 .... <= Input Layer
- Y1, Y2, ... <= Output Layer
-  S =  Σ X<sub>i</sub> W<sub>i</sub>
    - combinaions of X and W based on path for each prticular layer
- Hidden Layer : H1, H2, ...
- Wi <==> Weights  
- Bias  : less than 1; B1, B2, ...
- Activation with sigmoid fn => The output for a single layer (process of forward propagation)
- Z ==> S + bias
- Sigmoid Fn : $$ x = {\\  1 \over 1 + e^{-z} } $$ can also be taken as (1- e * x)
- Compare resulatant of ouput with Original value (given); if they are same, procedure can be stopped; if not we apply baclkward propation for updating weights
- Backward Propagation : resumes where we left off, ie; backward (from right-to-left)
    - New val of wi, $$ wi =  Old_Val_of_wi - [(eta_symbol) * derivative of { Error \over old_Val_of_wi } ]$$
    - ie; ivide, eta vechu all related weights for each output nokkanam/hidden layer 
        ie; differential of error for each dependant of Y<sub>i</sub> and/or H<sub>i</sub>
     - (eta) is,  learning rate  ; decimals less than 1
     - Chain rule of partial derivatives
     * Str reaches left End of first cycle of this process : End of first iteration
         1. Apply the same forward propagation;
         2. Check values
         3. If (!notEqual); 
            - Apply backward Propagation
         4. Else 
             - Procedure terminates when it's done. 
- Gradient--- procedure => uses derivations/ differential calc
- Gradient Descent
    - Error is taken by mean_quare_error
    - 
    - if this get's too complex, vanishing gradient will occur; procedures like LSDM is used
- Manual process takes more than an 1hr
- Steps :
    1. Get Inputs X1, X2, X3 ...
    2. Compute S, add bias to get Z
    3. Apply activation with sigmoid fn; marks end of forward propagation; to get resultant output
    4. Loop begins
    5. Updation of Weights : Checking as mentioned above
    - if found dissimilar; apply Backward Propagation until target value == output value
    6. Terminate Process

### Note : 
- When there is strict/necessary co-relation between data, it is called neural network
- RBM & Autoencoders
- overfitting & underfitting => L1, L2 regularization == penalty ii. dataset augmentation iii bagging & ensemble models iv early stopping ; adam optimiser
- epochs entha? epochs kodukannam or itll run for a long time.
- DNN is ANN with multiple hidden layers
- CNN for image 
    - filters and kernels, convolution ; pooling
- RNN for sequential data
    - Problems : Vanishing gradient, exploding gradient; Soln's like : LSTM
    - LSTM, GRU, Gated RNN, Noturn encoders
- Multilayer Perceptron == Deep Feedforward network === feedforward neural network
- z == linear regression; activation formular from logistical
- ANN - speech recognition, anomaly detection, audio generation, spell check
- Activation fn s : * can be applied on hidden layer
 - Linear : fn is same as z
 - Step : if z less than 0, 0; greater than or equal to 0 ; is; like step fn in mathematics
 - Sigmpid : as above
 - Softmax : extension of sigmoid; e^x / summ of e^x; CNN; multiple inputs
 - ReLU : ; used for CNN
 - Hyperbolic : tanh
 $$ tanh = \frac{\\ e^x - e^-x}{e^x + e^-x} $$
 - loss fn - cross entropy(classification), log loss, hinge loss, exponential loss, 

### Practicals

#### Program 1

In [146]:
import numpy as np

In [147]:
in_sam = np.array([[1,0,1],[1,1,1],[0,1,0],[0,1,1]])
out_sam = np.array([[1],[1],[0],[0]])
in_sam

array([[1, 0, 1],
       [1, 1, 1],
       [0, 1, 0],
       [0, 1, 1]])

In [148]:
out_sam

array([[1],
       [1],
       [0],
       [0]])

In [149]:
#weights
#random.seed(); so that values remain same everytime we run
np.random.seed(10)
weights = np.random.random([3,1])
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [150]:
bias = 0.02 
sum = bias + np.dot(in_sam, weights)
sum


array([[1.42496888],
       [1.44572083],
       [0.04075195],
       [0.67440018]])

In [151]:
def activation(x):
    return 1/(1+np.exp(-x))
pred_out = activation(sum)
pred_out

array([[0.8061162 ],
       [0.80933899],
       [0.51018658],
       [0.66248773]])

In [152]:
error = out_sam - pred_out
error

array([[ 0.1938838 ],
       [ 0.19066101],
       [-0.51018658],
       [-0.66248773]])

when taking ; we must check whether matrix mult is possible or not #found by .shape
and then perform adjustment #adjustment.shape

kaggle mnist data set (structured & professional ) ; tf ; unstructured vechu padikka

In [153]:
'''conda install theanos
pip install keras 
#restart kernel
pip install tensorflow
# theano '''

'conda install theanos\npip install keras \n#restart kernel\npip install tensorflow\n# theano '

In [154]:
import tensorflow
import keras


In [155]:
keras.__version__


'2.12.0'

In [156]:
import numpy as np
import tensorflow.keras as tf
import matplotlib.pyplot as plt
mnist  = tf.datasets.mnist
'''(xtrain) = '''

'(xtrain) = '

In [157]:
#len(xtrain) # len od training sdataset 

In [158]:
import numpy as np
import pandas as pd
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from keras.models import Sequential
from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
from keras.callbacks import EarlyStopping

In [159]:
data = pd.read_csv('una.csv',usecols=['TITLE','CATEGORY'],on_bad_lines='skip')
data.CATEGORY.value_counts()

CATEGORY
e    152469
b    115967
t    108344
m     45639
Name: count, dtype: int64

In [160]:
num_of_categories = 45000
shuffled = data.reindex(np.random.permutation(data.index))
e = shuffled[shuffled['CATEGORY']=='e'[:num_of_categories]]
b = shuffled[shuffled['CATEGORY']=='b'[:num_of_categories]]
t = shuffled[shuffled['CATEGORY']=='t'[:num_of_categories]]
m = shuffled[shuffled['CATEGORY']=='m'[:num_of_categories]]
concated = pd.concat([e,b,t,m],ignore_index=True)

In [161]:
#Shuffle the dataset
concated = concated.reindex(np.random.permutation(concated.index))
concated['LABEL']=0


In [162]:
#Perform one-hot encoding on the labels data
concated.loc[concated['CATEGORY']=='e','LABEL'] = 0
concated.loc[concated['CATEGORY']=='b','LABEL'] = 1
concated.loc[concated['CATEGORY']=='t','LABEL'] = 2
concated.loc[concated['CATEGORY']=='m','LABEL'] = 3
print(concated['LABEL'][:10])

92153     0
89855     0
109502    0
272462    2
360158    2
365118    2
358861    2
171018    1
140668    0
327934    2
Name: LABEL, dtype: int64


In [163]:
labels = to_categorical(concated['LABEL'],num_classes=4)
print(labels[:10])

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]


In [164]:
if 'CATEGORY' in concated.keys():
    concated.drop(['CATEGORY'],axis=1)

In [165]:
#Perform tokenization and identify the number of unique tokens
n_most_common_words = 8000
max_len = 130
'''This class allows to vectorize a text corpus, by turning each text into
either a sequence of integers (each integer being the index of a token in
a dictionary) or into a vector '''
tokenizer = Tokenizer(num_words=n_most_common_words,filters='!"#$%&()*+,-./:;<+>?@[\]^_`{|}~',lower=True)
tokenizer.fit_on_texts(concated['TITLE'].values)
sequences = tokenizer.texts_to_sequences(concated['TITLE'].values)
word_index = tokenizer.word_index
X = pad_sequences(sequences,maxlen=max_len)

In [170]:
#Split the dataset into training and testing sets. Also, define epochs, batch size, and labels for the same
X_train,X_test,y_train,y_test =train_test_split(X,labels,test_size=0.25,random_state=42)


In [171]:
epochs=2
emb_dim=128
batch_size=256
labels[:2]

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.]], dtype=float32)

In [172]:
#Code the LSTM model and fit the same into the processed data.
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

(316814, 130) (316814, 4) (105605, 130) (105605, 4)


In [173]:
model = Sequential()
#Turns positive integers (indexes) into dense vectors of fixed size
model.add(Embedding(n_most_common_words,emb_dim,input_length=X.shape[1]))
#perform dropout
model.add(SpatialDropout1D(0.7))
#First LSTM layer with Dropout regularisation. To avoid overfitting
model.add(LSTM(64,dropout=0.7,recurrent_dropout=0.7))
#The output layer
model.add(Dense(4,activation='softmax'))
#perform optimization
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['acc'])
print(model.summary)

<bound method Model.summary of <keras.engine.sequential.Sequential object at 0x00000255DDB05E10>>


In [174]:
history = model.fit(X_train,y_train,epochs=epochs,batch_size=batch_size,validation_split=0.2,callbacks=[EarlyStopping(monitor='val_loss',min_delta=0,patience=0,verbose=0,mode="auto",baseline=None,restore_best_weights=False,start_from_epoch=0)])

Epoch 1/2
991/991 [==============================] - 917s 923ms/step - loss: 0.5058 - acc: 0.8046 - val_loss: 0.2343 - val_acc: 0.9197
Epoch 2/2
991/991 [==============================] - 992s 1s/step - loss: 0.2686 - acc: 0.9072 - val_loss: 0.2138 - val_acc: 0.9268


In [ ]:
#Evaluate the results on training and testing sets and obtain accuracy of the
accr = model.evaluate(X_test,y_test)
print('Test set\n Loss:{:0.3f}\n Accuracy: {:0.3f}'.format(accr[0],accr[1]))

In [ ]:
#Perform label predictions against random data.
txt = ["Stocks fall on weak china export data"]
seq = tokenizer.texts_to_sequences(txt)
padded = pad_sequences(seq,maxlen=max_len)
predict = model.predict(padded)
labels = ['entertainment','business','science/tech','health']
print(predict,labels[np.argmax(predict)])