## Neural Network

In [1]:
import numpy as np

In [2]:
input_samples = np.array([[1,0,1],[1,1,1],[0,1,0],[0,1,1]])
output_samples = np.array([[1],[1],[0],[0]])

In [3]:
input_samples

array([[1, 0, 1],
       [1, 1, 1],
       [0, 1, 0],
       [0, 1, 1]])

In [4]:
output_samples

array([[1],
       [1],
       [0],
       [0]])

In [5]:
#### Weights
np.random.seed(10)
weights = np.random.random((3,1))
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [6]:
sum = 0.02 + np.dot(input_samples,weights)
sum

array([[1.42496888],
       [1.44572083],
       [0.04075195],
       [0.67440018]])

In [7]:
### creating activation function (sigmoid)
def activation(x):   
  return 1 / ( 1 + np.exp(-x))

In [16]:
predicted_output = activation(sum)
predicted_output

array([[0.8061162 ],
       [0.80933899],
       [0.51018658],
       [0.66248773]])

In [17]:
sum = 0.02 + np.dot(input_samples,weights)
predicted_output = activation(sum)
error = output_samples - predicted_output
error

array([[ 0.1938838 ],
       [ 0.19066101],
       [-0.51018658],
       [-0.66248773]])

In [18]:
def gradient(x):
  return x * (1-x)

In [21]:
sum = 0.02 + np.dot(input_samples,weights)
predicted_output = activation(sum)
error = output_samples - predicted_output
adjustment = error * gradient(predicted_output)   ### gradient descent
weights += np.dot(input_samples.T,adjustment) # changing the  previous weight to the new weight
error

array([[ 0.19840629],
       [ 0.2367044 ],
       [-0.44881698],
       [-0.58413931]])

In [14]:
input_samples.shape # justification for taking the transpose

(4, 3)

In [20]:
adjustment.shape

(4, 1)

In [12]:
input_samples.T.shape #we take the transpose T because input sample shape is (4,3). So to multiply with adjustment of shape (4,1)

(3, 4)

In [13]:
adjustment.shape

(4, 1)

In [22]:
for i in range(1000):
  sum = 0.02 + np.dot(input_samples,weights)
  predicted_output = activation(sum)
  error = output_samples - predicted_output
  adjustment = error * gradient(predicted_output)   ### gradient descent
  weights += np.dot(input_samples.T,adjustment)
error

array([[ 0.00079506],
       [ 0.03362751],
       [-0.02279628],
       [-0.03394494]])

In [23]:
predicted_output.round()

array([[1.],
       [1.],
       [0.],
       [0.]])